---
group: hospital_referral
fields:
  - "Woman referred to hospital"
  - "Woman not referred to hospital: {referred_hosp_notdone} {referred_hosp_notdone_other}"
  - "Danger sign(s): {danger_signs}"
  - "Severe hypertension: {bp_systolic_repeat}/{bp_diastolic_repeat} mmHg"
  - "Hypertension and symptom of severe pre-eclampsia: {symp_sev_preeclampsia}"
  - "Woman not referred to hospital: {referred_hosp_notdone} {referred_hosp_notdone_other}"
  - "Pre-eclampsia diagnosis"
  - "Severe pre-eclampsia diagnosis"
  - "Fever: {body_temp_repeat}ºC"
  - "Abnormal pulse rate: {pulse_rate_repeat}bpm"
  - "Respiratory distress: {repiratory_exam}, {respiratory_exam_other}"
  - "Low oximetry: {oximetry}%"
  - "Abnormal cardiac exam: {cardiac_exam}, {cardiac_exam_other}"
  - "Abnormal breast exam: {breast_exam}, {breast_exam_other}"
  - "Abnormal abdominal exam: {abdominal_exam}, {abdominal_exam_other}"
  - "Abnormal pelvic exam: {pelvic_exam}, {pelvic_exam_other}"
  - "No fetal heartbeat observed"
  - "Abnormal fetal heart rate: {fetal_heart_rate_repeat}bpm"

---
group: reason_for_visit
fields:
  - "Reason for coming to facility: {contact_reason}"
  - "Specific complaint(s): {specific_complaint}, {specific_complaint_other}"

---
group: demographic_info
fields:
  - "Highest level of school: {educ_level}"
  - "Marital status: {marital_status}"
  - "Occupation: {occupation}, {occupation_other}"

---
group: current_pregnancy
fields:
  - "GA: {gest_age} weeks"
  - "EDD: {edd}"
  - "Ultrasound date: {ultrasound_date}"
  - "No. of fetuses: {no_of_fetuses}"
  - "Fetal presentation: {fetal_presentation}"
  - "Amniotic fluid: {amniotic_fluid}"
  - "Placenta location: {placenta_location}"

---
group: obstetric_history
fields:
  - "GP: {gravida}{parity}"
  - "No. of pregnancies lost/ended: {miscarriages_abortions}"
  - "No. of live births: {live_births}"
  - "No. of stillbirths: {stillbirths}"
  - "No. of C-sections: {c_sections}"
  - "Past pregnancy problems: {prev_preg_comps}, {prev_preg_comps_other}"
  - "Past alcohol / substances used: {substances_used}, {substances_used_other}"

---
group: medical_history
fields:
  - "Allergies: {allergies}, {allergies_other}"
  - "Surgeries: {surgeries}, {surgeries_other_gyn_proced}, {surgeries_other}"
  - "Chronic health conditions: {health_conditions}, {health_conditions_other}"
  - "HIV diagnosis date: {hiv_diagnosis_date}"
  - "HIV diagnosis date unknown"