---
group: hospital_referral
fields:
  - template: "Woman referred to hospital"
    relevance: "referred_hosp == 'Yes'"

  - template: "Woman not referred to hospital: {referred_hosp_notdone} {referred_hosp_notdone_other}"
    relevance: "referred_hosp == 'No'"

  - template: "Danger sign(s): {danger_signs}"
    relevance: "danger_signs == 'Bleeding vaginally' || danger_signs ==  'Central cyanosis' || danger_signs ==  'Convulsing' || danger_signs ==  'Fever' || danger_signs ==  'Headache and visual disturbance' || danger_signs ==  'Imminent delivery' || danger_signs ==  'Labour' || danger_signs ==  'Looks very ill' || danger_signs ==  'Severe vomiting' || danger_signs ==  'Severe pain' || danger_signs ==  'Severe abdominal pain' || danger_signs ==  'Unconscious'"

  - template: "Severe hypertension: {bp_systolic_repeat}/{bp_diastolic_repeat} mmHg"
    relevance: "severe_hypertension == 1 && contact_no == 1"

  - template: "Hypertension and symptom of severe pre-eclampsia: {symp_sev_preeclampsia}"
    relevance: "hypertension == 1 && (symp_sev_preeclampsia.contains('Severe headache') || symp_sev_preeclampsia.contains('Blurred vision') || symp_sev_preeclampsia.contains('Epigastric pain') || symp_sev_preeclampsia.contains('Dizziness') || symp_sev_preeclampsia.contains('Vomiting'))"

  - template: "Pre-eclampsia diagnosis"
    relevance: "preeclampsia == 1 && contact_no == 1"

  - template: "Severe pre-eclampsia diagnosis"
    relevance: "severe_preeclampsia == 1 && contact_no == 1"

  - template: "Fever: {body_temp_repeat}ºC"
    relevance: "body_temp_repeat >= 38"

  - template: "Abnormal pulse rate: {pulse_rate_repeat}bpm"
    relevance: "pulse_rate_repeat < 60 || pulse_rate_repeat > 100"

  - template: "Respiratory distress: {repiratory_exam}, {respiratory_exam_other}"
    relevance: "respiratory_exam.contains('Dyspnoea') || respiratory_exam.contains('Cough') || respiratory_exam.contains('Rapid breathing') || respiratory_exam.contains('Slow breathing') || respiratory_exam.contains('Wheezing') || respiratory_exam.contains('Rales') || respiratory_exam.contains('Other')"

  - template: "Low oximetry: {oximetry}%"
    relevance: "oximetry < 92"

  - template: "Abnormal cardiac exam: {cardiac_exam}, {cardiac_exam_other}"
    relevance: "cardiac_exam_other.contains('Heart murmur') || cardiac_exam.contains('Weak pulse') || cardiac_exam.contains('Tachycardia') || cardiac_exam.contains('Bradycardia') || cardiac_exam.contains('Arrhythmia') || cardiac_exam.contains('Cyanosis') || cardiac_exam.contains('Cold sweats') || cardiac_exam.contains('Other')"

  - template: "Abnormal breast exam: {breast_exam}, {breast_exam_other}"
    relevance: "breast_exam.contains('Nodule') || breast_exam.contains('Discharge') || breast_exam.contains('Flushing') || breast_exam.contains('Local pain') || breast_exam.contains('Bleeding') || breast_exam.contains('Increased temperature') || breast_exam.contains('Other')"

  - template: "Abnormal abdominal exam: {abdominal_exam}, {abdominal_exam_other}"
    relevance: "abdominal_exam.contains('Mass/tumour') || abdominal_exam.contains('Pain on superficial palpation') || abdominal_exam.contains('Pain on deep palpation') || abdominal_exam.contains('Painful decompression') || abdominal_exam.contains('Other')"

  - template: "Abnormal pelvic exam: {pelvic_exam}, {pelvic_exam_other}"
    relevance: "pelvic_exam.contains('Physiological vaginal discharge') || pelvic_exam.contains('Abnormal vaginal discharge') || pelvic_exam.contains('Evidence of amniotic fluid') || pelvic_exam.contains('Foul-smelling vaginal discharge') || pelvic_exam.contains('Clusters of erythematous papules') || pelvic_exam.contains('Vesicles') || pelvic_exam.contains('Genital ulcer') || pelvic_exam.contains('Genital pain') || pelvic_exam.contains('Tender bilateral inguinal and femoral lymphadenopathy') || pelvic_exam.contains('Cervical friability') || pelvic_exam.contains('Mucopurulent cervicitis') || pelvic_exam.contains('Tender unilateral lymphadenopathy') || pelvic_exam.contains('Curd-like vaginal discharge') || pelvic_exam.contains('Other')"

  - template: "No fetal heartbeat observed"
    relevance: "fetal_heartbeat == 'No'"

  - template: "Abnormal fetal heart rate: {fetal_heart_rate_repeat}bpm"
    relevance: "fetal_heart_rate_repeat < 110 || fetal_heart_rate_repeat > 160"

---
group: reason_for_visit
fields:
  - template: "Reason for coming to facility: {contact_reason}"
    relevance: "contact_reason != ''"

  - template: "Specific complaint(s): {specific_complaint}, {specific_complaint_other}"
    relevance: "specific_complaint != ''"

---
group: demographic_info
fields:
  - template: "Highest level of school: {educ_level}"
    relevance: "educ_level != ''"

  - template: "Marital status: {marital_status}"
    relevance: "marital_status != ''"

  - template: "Occupation: {occupation}, {occupation_other}"
    relevance: "occupation != ''"

---
group: current_pregnancy
fields:
  - template: "GA: {gest_age} weeks"
    relevance: ""

  - template: "EDD: {edd}"
    relevance: ""

  - template: "Ultrasound date: {ultrasound_date}"
    relevance: "ultrasound_date != ''"

  - template: "No. of fetuses: {no_of_fetuses}"
    relevance: ""

  - template: "Fetal presentation: {fetal_presentation}"
    relevance: "fetal_presentation != ''"

  - template: "Amniotic fluid: {amniotic_fluid}"
    relevance: "amniotic_fluid != ''"

  - template: "Placenta location: {placenta_location}"
    relevance: "placenta_location != ''"

---
group: obstetric_history
fields:
  - template: "GP: {gravida}{parity}"
    relevance: ""

  - template: "No. of pregnancies lost/ended: {miscarriages_abortions}"
    relevance: "contact_no == 1 || miscarriages_abortions > 0"

  - template: "No. of live births: {live_births}"
    relevance: "contact_no == 1 || live_births > 0"

  - template: "No. of stillbirths: {stillbirths}"
    relevance: "contact_no == 1 || stillbirths > 0"

  - template: "No. of C-sections: {c_sections}"
    relevance: "contact_no == 1 || c_sections > 0"

  - template: "Past pregnancy problems: {prev_preg_comps}, {prev_preg_comps_other}"
    relevance: "contact_no == 1 || (!prev_preg_comps.contains('dont_know') || !prev_preg_comps.contains('none'))"

  - template: "Past alcohol / substances used: {substances_used}, {substances_used_other}"
    relevance: "contact_no == 1 || (!substances_used.contains('none') && substances_used.size() > 0) "

---
group: medical_history
fields:
  - template: "Allergies: {allergies}, {allergies_other}"
    relevance: "allergies != '' || contact_no  == 1"

  - template: "Surgeries: {surgeries}, {surgeries_other_gyn_proced}, {surgeries_other}"
    relevance: "surgeries != '' || contact_no  == 1"

  - template: "Chronic health conditions: {health_conditions}, {health_conditions_other}"
    relevance: "health_conditions != '' || contact_no  == 1"

  - template: "HIV diagnosis date: {hiv_diagnosis_date}"
    relevance: "hiv_diagnosis_date != '' || contact_no  == 1"

  - template: "HIV diagnosis date unknown"
    relevance: "hiv_diagnosis_date_unknown.contains('Unknown HIV Date') || contact_no  == 1"
---
group: immunisation_status
fields:
  - template: "TT immunisation status: "
    relevance: "allergies != '' || contact_no  == 1"

  - template: "Surgeries: {surgeries}, {surgeries_other_gyn_proced}, {surgeries_other}"
    relevance: "surgeries != '' || contact_no  == 1"

  - template: "Chronic health conditions: {health_conditions}, {health_conditions_other}"
    relevance: "health_conditions != '' || contact_no  == 1"

  - template: "HIV diagnosis date: {hiv_diagnosis_date}"
    relevance: "hiv_diagnosis_date != '' || contact_no  == 1"

  - template: "HIV diagnosis date unknown"
    relevance: "hiv_diagnosis_date_unknown.contains('Unknown HIV Date') || contact_no  == 1"
